{% set data = load_setup_py_data() %}

package:
  name: openalea.deploy
  version: {{ data.get('version') }}

source:
  path: ..

build:
  preserve_egg_dir: True
  number: 0
  script: python setup.py install

requirements:
  build:
    - python {{PY_VER}}* [not win]
    - python {{PY_VER}}  [win]
    - setuptools
  run:
    - python {{PY_VER}}* [not win]
    - python {{PY_VER}}  [win]
    - setuptools
    - path

test:
  imports:
    - openalea.deploy

about:
  home: http://github.com/openalea/deploy
  license: Cecill-C License
  summary: OpenAlea.Deploy support the installation of OpenAlea packages via the network and manage their dependencies.
